server:
  port: 8888
  error:
    whitelabel:
      enabled: false


eureka:
  instance:
    hostname: ${discovery.host:localhost}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 60
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
    metadata-map:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
      
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: configuration.log
  level:
    com.springframework.cloud.netflix.eureka: DEBUG
    
management:
  security:
    enabled: false
  port: 7882
  info:
    git:
      mode: full
  context-path: /manage
  
---
spring:
  profiles: dockerC
discovery:
    host: eurekad
    